site_name: Better Networks
nav:
  - Home: index.md
  - Team: team.md
  - Videos: videos.md
  - Publications: publications.md
  - Challenges: challenges.md
  - Education: education.md
theme:
  name: null
  custom_dir: 'cinder'